//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TuringMachine.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class TuringMachineLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, VALID_CHAR=11, BLOCK_COMMENT=12, LINE_COMMENT=13, WS=14;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "VALID_CHAR", "BLOCK_COMMENT", "LINE_COMMENT", "WS"
	};


	public TuringMachineLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public TuringMachineLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'->'", "';'", "','", "'L'", "'R'", "'E'", "'P'", "'none'", "'notNone'", 
		"'any'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, "VALID_CHAR", 
		"BLOCK_COMMENT", "LINE_COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "TuringMachine.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static TuringMachineLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x10', '\x61', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\a', '\r', '\x46', '\n', '\r', 
		'\f', '\r', '\xE', '\r', 'I', '\v', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\a', '\xE', 'T', '\n', '\xE', '\f', '\xE', '\xE', '\xE', 
		'W', '\v', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x6', '\xF', 
		'\\', '\n', '\xF', '\r', '\xF', '\xE', '\xF', ']', '\x3', '\xF', '\x3', 
		'\xF', '\x3', 'G', '\x2', '\x10', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', 
		'\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', 
		'\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', 
		'\x10', '\x3', '\x2', '\x5', '\x5', '\x2', '\x32', ';', '\x43', '\\', 
		'\x63', '|', '\x4', '\x2', '\f', '\f', '\xF', '\xF', '\x5', '\x2', '\v', 
		'\f', '\xE', '\xF', '\"', '\"', '\x2', '\x63', '\x2', '\x3', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x3', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '\x5', '\"', '\x3', '\x2', '\x2', '\x2', '\a', '$', 
		'\x3', '\x2', '\x2', '\x2', '\t', '&', '\x3', '\x2', '\x2', '\x2', '\v', 
		'(', '\x3', '\x2', '\x2', '\x2', '\r', '*', '\x3', '\x2', '\x2', '\x2', 
		'\xF', ',', '\x3', '\x2', '\x2', '\x2', '\x11', '.', '\x3', '\x2', '\x2', 
		'\x2', '\x13', '\x33', '\x3', '\x2', '\x2', '\x2', '\x15', ';', '\x3', 
		'\x2', '\x2', '\x2', '\x17', '?', '\x3', '\x2', '\x2', '\x2', '\x19', 
		'\x41', '\x3', '\x2', '\x2', '\x2', '\x1B', 'O', '\x3', '\x2', '\x2', 
		'\x2', '\x1D', '[', '\x3', '\x2', '\x2', '\x2', '\x1F', ' ', '\a', '/', 
		'\x2', '\x2', ' ', '!', '\a', '@', '\x2', '\x2', '!', '\x4', '\x3', '\x2', 
		'\x2', '\x2', '\"', '#', '\a', '=', '\x2', '\x2', '#', '\x6', '\x3', '\x2', 
		'\x2', '\x2', '$', '%', '\a', '.', '\x2', '\x2', '%', '\b', '\x3', '\x2', 
		'\x2', '\x2', '&', '\'', '\a', 'N', '\x2', '\x2', '\'', '\n', '\x3', '\x2', 
		'\x2', '\x2', '(', ')', '\a', 'T', '\x2', '\x2', ')', '\f', '\x3', '\x2', 
		'\x2', '\x2', '*', '+', '\a', 'G', '\x2', '\x2', '+', '\xE', '\x3', '\x2', 
		'\x2', '\x2', ',', '-', '\a', 'R', '\x2', '\x2', '-', '\x10', '\x3', '\x2', 
		'\x2', '\x2', '.', '/', '\a', 'p', '\x2', '\x2', '/', '\x30', '\a', 'q', 
		'\x2', '\x2', '\x30', '\x31', '\a', 'p', '\x2', '\x2', '\x31', '\x32', 
		'\a', 'g', '\x2', '\x2', '\x32', '\x12', '\x3', '\x2', '\x2', '\x2', '\x33', 
		'\x34', '\a', 'p', '\x2', '\x2', '\x34', '\x35', '\a', 'q', '\x2', '\x2', 
		'\x35', '\x36', '\a', 'v', '\x2', '\x2', '\x36', '\x37', '\a', 'P', '\x2', 
		'\x2', '\x37', '\x38', '\a', 'q', '\x2', '\x2', '\x38', '\x39', '\a', 
		'p', '\x2', '\x2', '\x39', ':', '\a', 'g', '\x2', '\x2', ':', '\x14', 
		'\x3', '\x2', '\x2', '\x2', ';', '<', '\a', '\x63', '\x2', '\x2', '<', 
		'=', '\a', 'p', '\x2', '\x2', '=', '>', '\a', '{', '\x2', '\x2', '>', 
		'\x16', '\x3', '\x2', '\x2', '\x2', '?', '@', '\t', '\x2', '\x2', '\x2', 
		'@', '\x18', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\a', '\x31', 
		'\x2', '\x2', '\x42', '\x43', '\a', ',', '\x2', '\x2', '\x43', 'G', '\x3', 
		'\x2', '\x2', '\x2', '\x44', '\x46', '\v', '\x2', '\x2', '\x2', '\x45', 
		'\x44', '\x3', '\x2', '\x2', '\x2', '\x46', 'I', '\x3', '\x2', '\x2', 
		'\x2', 'G', 'H', '\x3', '\x2', '\x2', '\x2', 'G', '\x45', '\x3', '\x2', 
		'\x2', '\x2', 'H', 'J', '\x3', '\x2', '\x2', '\x2', 'I', 'G', '\x3', '\x2', 
		'\x2', '\x2', 'J', 'K', '\a', ',', '\x2', '\x2', 'K', 'L', '\a', '\x31', 
		'\x2', '\x2', 'L', 'M', '\x3', '\x2', '\x2', '\x2', 'M', 'N', '\b', '\r', 
		'\x2', '\x2', 'N', '\x1A', '\x3', '\x2', '\x2', '\x2', 'O', 'P', '\a', 
		'\x31', '\x2', '\x2', 'P', 'Q', '\a', '\x31', '\x2', '\x2', 'Q', 'U', 
		'\x3', '\x2', '\x2', '\x2', 'R', 'T', '\n', '\x3', '\x2', '\x2', 'S', 
		'R', '\x3', '\x2', '\x2', '\x2', 'T', 'W', '\x3', '\x2', '\x2', '\x2', 
		'U', 'S', '\x3', '\x2', '\x2', '\x2', 'U', 'V', '\x3', '\x2', '\x2', '\x2', 
		'V', 'X', '\x3', '\x2', '\x2', '\x2', 'W', 'U', '\x3', '\x2', '\x2', '\x2', 
		'X', 'Y', '\b', '\xE', '\x2', '\x2', 'Y', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', 'Z', '\\', '\t', '\x4', '\x2', '\x2', '[', 'Z', '\x3', '\x2', '\x2', 
		'\x2', '\\', ']', '\x3', '\x2', '\x2', '\x2', ']', '[', '\x3', '\x2', 
		'\x2', '\x2', ']', '^', '\x3', '\x2', '\x2', '\x2', '^', '_', '\x3', '\x2', 
		'\x2', '\x2', '_', '`', '\b', '\xF', '\x2', '\x2', '`', '\x1E', '\x3', 
		'\x2', '\x2', '\x2', '\x6', '\x2', 'G', 'U', ']', '\x3', '\b', '\x2', 
		'\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
