//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TuringMachine.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


#pragma warning disable 3021


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ITuringMachineListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class TuringMachineBaseListener : ITuringMachineListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile([NotNull] TuringMachineParser.FileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile([NotNull] TuringMachineParser.FileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.machine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMachine([NotNull] TuringMachineParser.MachineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.machine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMachine([NotNull] TuringMachineParser.MachineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.step"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStep([NotNull] TuringMachineParser.StepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.step"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStep([NotNull] TuringMachineParser.StepContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.finalMConfiguration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFinalMConfiguration([NotNull] TuringMachineParser.FinalMConfigurationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.finalMConfiguration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFinalMConfiguration([NotNull] TuringMachineParser.FinalMConfigurationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.operations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperations([NotNull] TuringMachineParser.OperationsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.operations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperations([NotNull] TuringMachineParser.OperationsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperation([NotNull] TuringMachineParser.OperationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperation([NotNull] TuringMachineParser.OperationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.moveLeft"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMoveLeft([NotNull] TuringMachineParser.MoveLeftContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.moveLeft"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMoveLeft([NotNull] TuringMachineParser.MoveLeftContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.moveRight"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMoveRight([NotNull] TuringMachineParser.MoveRightContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.moveRight"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMoveRight([NotNull] TuringMachineParser.MoveRightContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.erase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterErase([NotNull] TuringMachineParser.EraseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.erase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitErase([NotNull] TuringMachineParser.EraseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.print"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint([NotNull] TuringMachineParser.PrintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.print"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint([NotNull] TuringMachineParser.PrintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NoneSymbolSpecification</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoneSymbolSpecification([NotNull] TuringMachineParser.NoneSymbolSpecificationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NoneSymbolSpecification</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoneSymbolSpecification([NotNull] TuringMachineParser.NoneSymbolSpecificationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AnySymbolSpecification</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnySymbolSpecification([NotNull] TuringMachineParser.AnySymbolSpecificationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AnySymbolSpecification</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnySymbolSpecification([NotNull] TuringMachineParser.AnySymbolSpecificationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AnyOrNoneSymbolSpecification</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnyOrNoneSymbolSpecification([NotNull] TuringMachineParser.AnyOrNoneSymbolSpecificationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AnyOrNoneSymbolSpecification</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnyOrNoneSymbolSpecification([NotNull] TuringMachineParser.AnyOrNoneSymbolSpecificationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SymbolSymbolSpecification</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSymbolSymbolSpecification([NotNull] TuringMachineParser.SymbolSymbolSpecificationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SymbolSymbolSpecification</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSymbolSymbolSpecification([NotNull] TuringMachineParser.SymbolSymbolSpecificationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.mConfiguration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMConfiguration([NotNull] TuringMachineParser.MConfigurationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.mConfiguration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMConfiguration([NotNull] TuringMachineParser.MConfigurationContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
