//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TuringMachine.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


#pragma warning disable 3021

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="TuringMachineParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.CLSCompliant(false)]
public interface ITuringMachineListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile([NotNull] TuringMachineParser.FileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile([NotNull] TuringMachineParser.FileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.machine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMachine([NotNull] TuringMachineParser.MachineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.machine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMachine([NotNull] TuringMachineParser.MachineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.step"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStep([NotNull] TuringMachineParser.StepContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.step"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStep([NotNull] TuringMachineParser.StepContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.finalMConfiguration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFinalMConfiguration([NotNull] TuringMachineParser.FinalMConfigurationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.finalMConfiguration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFinalMConfiguration([NotNull] TuringMachineParser.FinalMConfigurationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.operations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperations([NotNull] TuringMachineParser.OperationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.operations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperations([NotNull] TuringMachineParser.OperationsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperation([NotNull] TuringMachineParser.OperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperation([NotNull] TuringMachineParser.OperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.moveLeft"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMoveLeft([NotNull] TuringMachineParser.MoveLeftContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.moveLeft"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMoveLeft([NotNull] TuringMachineParser.MoveLeftContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.moveRight"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMoveRight([NotNull] TuringMachineParser.MoveRightContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.moveRight"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMoveRight([NotNull] TuringMachineParser.MoveRightContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.erase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterErase([NotNull] TuringMachineParser.EraseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.erase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitErase([NotNull] TuringMachineParser.EraseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrint([NotNull] TuringMachineParser.PrintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrint([NotNull] TuringMachineParser.PrintContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NoneSymbolSpecification</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoneSymbolSpecification([NotNull] TuringMachineParser.NoneSymbolSpecificationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NoneSymbolSpecification</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoneSymbolSpecification([NotNull] TuringMachineParser.NoneSymbolSpecificationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AnySymbolSpecification</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnySymbolSpecification([NotNull] TuringMachineParser.AnySymbolSpecificationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AnySymbolSpecification</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnySymbolSpecification([NotNull] TuringMachineParser.AnySymbolSpecificationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AnyOrNoneSymbolSpecification</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnyOrNoneSymbolSpecification([NotNull] TuringMachineParser.AnyOrNoneSymbolSpecificationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AnyOrNoneSymbolSpecification</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnyOrNoneSymbolSpecification([NotNull] TuringMachineParser.AnyOrNoneSymbolSpecificationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SymbolSymbolSpecification</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSymbolSymbolSpecification([NotNull] TuringMachineParser.SymbolSymbolSpecificationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SymbolSymbolSpecification</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSymbolSymbolSpecification([NotNull] TuringMachineParser.SymbolSymbolSpecificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.mConfiguration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMConfiguration([NotNull] TuringMachineParser.MConfigurationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.mConfiguration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMConfiguration([NotNull] TuringMachineParser.MConfigurationContext context);
}
