
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.provision "docker" do |d|
  
  end
  
  config.vm.synced_folder ".", "/vagrant_data"

  config.vm.provision :shell, path: "bootstrap.sh", run: "always"
end
