//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TuringMachine.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="TuringMachineParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ITuringMachineVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="TuringMachineParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] TuringMachineParser.FileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TuringMachineParser.machine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMachine([NotNull] TuringMachineParser.MachineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TuringMachineParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] TuringMachineParser.LineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TuringMachineParser.finalMConfiguration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFinalMConfiguration([NotNull] TuringMachineParser.FinalMConfigurationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TuringMachineParser.operations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperations([NotNull] TuringMachineParser.OperationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TuringMachineParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperation([NotNull] TuringMachineParser.OperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TuringMachineParser.moveLeft"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMoveLeft([NotNull] TuringMachineParser.MoveLeftContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TuringMachineParser.moveRight"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMoveRight([NotNull] TuringMachineParser.MoveRightContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TuringMachineParser.erase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitErase([NotNull] TuringMachineParser.EraseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TuringMachineParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrint([NotNull] TuringMachineParser.PrintContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>None</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNone([NotNull] TuringMachineParser.NoneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Any</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAny([NotNull] TuringMachineParser.AnyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AnyNone</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnyNone([NotNull] TuringMachineParser.AnyNoneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Symbol</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSymbol([NotNull] TuringMachineParser.SymbolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TuringMachineParser.mConfiguration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMConfiguration([NotNull] TuringMachineParser.MConfigurationContext context);
}
