//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TuringMachine.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="TuringMachineParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ITuringMachineListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile([NotNull] TuringMachineParser.FileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile([NotNull] TuringMachineParser.FileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.machine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMachine([NotNull] TuringMachineParser.MachineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.machine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMachine([NotNull] TuringMachineParser.MachineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] TuringMachineParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] TuringMachineParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.finalMConfiguration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFinalMConfiguration([NotNull] TuringMachineParser.FinalMConfigurationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.finalMConfiguration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFinalMConfiguration([NotNull] TuringMachineParser.FinalMConfigurationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.operations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperations([NotNull] TuringMachineParser.OperationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.operations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperations([NotNull] TuringMachineParser.OperationsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperation([NotNull] TuringMachineParser.OperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperation([NotNull] TuringMachineParser.OperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.moveLeft"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMoveLeft([NotNull] TuringMachineParser.MoveLeftContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.moveLeft"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMoveLeft([NotNull] TuringMachineParser.MoveLeftContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.moveRight"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMoveRight([NotNull] TuringMachineParser.MoveRightContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.moveRight"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMoveRight([NotNull] TuringMachineParser.MoveRightContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.erase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterErase([NotNull] TuringMachineParser.EraseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.erase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitErase([NotNull] TuringMachineParser.EraseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrint([NotNull] TuringMachineParser.PrintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrint([NotNull] TuringMachineParser.PrintContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>None</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNone([NotNull] TuringMachineParser.NoneContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>None</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNone([NotNull] TuringMachineParser.NoneContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Any</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAny([NotNull] TuringMachineParser.AnyContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Any</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAny([NotNull] TuringMachineParser.AnyContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AnyNone</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnyNone([NotNull] TuringMachineParser.AnyNoneContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AnyNone</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnyNone([NotNull] TuringMachineParser.AnyNoneContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Symbol</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSymbol([NotNull] TuringMachineParser.SymbolContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Symbol</c>
	/// labeled alternative in <see cref="TuringMachineParser.symbolSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSymbol([NotNull] TuringMachineParser.SymbolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TuringMachineParser.mConfiguration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMConfiguration([NotNull] TuringMachineParser.MConfigurationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TuringMachineParser.mConfiguration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMConfiguration([NotNull] TuringMachineParser.MConfigurationContext context);
}
